In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
  "name" : ['rohan','seema','mahesh','shruthi'],
  "marks" : [90,89,88,98],
  "city" : ['Delhi','Jaipur','Rampur','Barilly']
}

In [5]:
df =pd. DataFrame(dict1)
df

      name  marks     city
0    rohan     90    Delhi
1    seema     89   Jaipur
2   mahesh     88   Rampur
3  shruthi     98  Barilly

In [6]:
df.index =[1,2,3,4]
df

      name  marks     city
1    rohan     90    Delhi
2    seema     89   Jaipur
3   mahesh     88   Rampur
4  shruthi     98  Barilly

In [7]:
ser = pd.Series(np.random.rand(20))
ser

0     0.065193
1     0.125261
2     0.360280
3     0.405388
4     0.428739
5     0.200987
6     0.713957
7     0.445254
8     0.456819
9     0.866176
10    0.780405
11    0.294077
12    0.104823
13    0.356712
14    0.791408
15    0.341420
16    0.596704
17    0.345700
18    0.711538
19    0.720008
dtype: float64

In [8]:
type(ser)

pandas.core.series.Series

In [11]:
newdf = pd.DataFrame(np.random.rand(334,5),index = np.arange(334))
newdf

            0         1         2         3         4
0    0.599023  0.697541  0.827337  0.578492  0.446452
1    0.374038  0.656665  0.644977  0.495322  0.694402
2    0.737800  0.416521  0.819841  0.250721  0.949253
3    0.717827  0.974298  0.339361  0.308377  0.711697
4    0.440339  0.114775  0.742063  0.259132  0.135735
..        ...       ...       ...       ...       ...
329  0.811175  0.879591  0.323369  0.988741  0.678383
330  0.708159  0.882035  0.326024  0.478083  0.923150
331  0.638711  0.885493  0.662297  0.248676  0.264022
332  0.125141  0.468620  0.376018  0.937301  0.593854
333  0.227538  0.576309  0.262115  0.591536  0.902997

[334 rows x 5 columns]

In [12]:
newdf.head(3)

          0         1         2         3         4
0  0.599023  0.697541  0.827337  0.578492  0.446452
1  0.374038  0.656665  0.644977  0.495322  0.694402
2  0.737800  0.416521  0.819841  0.250721  0.949253

In [13]:
newdf.tail(3)

            0         1         2         3         4
331  0.638711  0.885493  0.662297  0.248676  0.264022
332  0.125141  0.468620  0.376018  0.937301  0.593854
333  0.227538  0.576309  0.262115  0.591536  0.902997

In [14]:
newdf.sort_index(axis = 0)

            0         1         2         3         4
0    0.599023  0.697541  0.827337  0.578492  0.446452
1    0.374038  0.656665  0.644977  0.495322  0.694402
2    0.737800  0.416521  0.819841  0.250721  0.949253
3    0.717827  0.974298  0.339361  0.308377  0.711697
4    0.440339  0.114775  0.742063  0.259132  0.135735
..        ...       ...       ...       ...       ...
329  0.811175  0.879591  0.323369  0.988741  0.678383
330  0.708159  0.882035  0.326024  0.478083  0.923150
331  0.638711  0.885493  0.662297  0.248676  0.264022
332  0.125141  0.468620  0.376018  0.937301  0.593854
333  0.227538  0.576309  0.262115  0.591536  0.902997

[334 rows x 5 columns]

In [15]:
newdf.drop(0,axis = 1)

            1         2         3         4
0    0.697541  0.827337  0.578492  0.446452
1    0.656665  0.644977  0.495322  0.694402
2    0.416521  0.819841  0.250721  0.949253
3    0.974298  0.339361  0.308377  0.711697
4    0.114775  0.742063  0.259132  0.135735
..        ...       ...       ...       ...
329  0.879591  0.323369  0.988741  0.678383
330  0.882035  0.326024  0.478083  0.923150
331  0.885493  0.662297  0.248676  0.264022
332  0.468620  0.376018  0.937301  0.593854
333  0.576309  0.262115  0.591536  0.902997

[334 rows x 4 columns]

In [16]:
newdf.dropna

<bound method DataFrame.dropna of             0         1         2         3         4
0    0.599023  0.697541  0.827337  0.578492  0.446452
1    0.374038  0.656665  0.644977  0.495322  0.694402
2    0.737800  0.416521  0.819841  0.250721  0.949253
3    0.717827  0.974298  0.339361  0.308377  0.711697
4    0.440339  0.114775  0.742063  0.259132  0.135735
..        ...       ...       ...       ...       ...
329  0.811175  0.879591  0.323369  0.988741  0.678383
330  0.708159  0.882035  0.326024  0.478083  0.923150
331  0.638711  0.885493  0.662297  0.248676  0.264022
332  0.125141  0.468620  0.376018  0.937301  0.593854
333  0.227538  0.576309  0.262115  0.591536  0.902997

[334 rows x 5 columns]>

In [17]:
newdf.dropna(inplace = True)